export const DASHBOARD = '/dashboard'
export const USERS = '/users'
export const USER_MANAGE = '/users/manage'
export const PROFILE = '/profile'
export const SETTINGS = '/settings'
export const SCHEDULES = '/schedules'
