export const DASHBOARD = '/dashboard'
export const USERS = '/users'
export const ROLES = '/roles'
export const PROFILE = '/profile'
export const SETTINGS = '/settings'
export const SCHEDULES = '/schedules'
