export enum ApiKeys {
    Auth = 'auth',
    Limits = 'limits',
    Organizations = 'organizations',
    OrganizationTypes = 'organization-types',
    Branches = 'branches',
    Plans = 'plans',
    Users = 'users',
    Roles = 'roles',
    People = 'people',
    Permissions = 'permissions',
    KBK = 'kbk',
    OKPD = 'okpd',
    KTRU = 'ktru',
    OKEI = 'okei',
    KOSGU = 'kosgu',
}
